### 0. Generate auth token
GET http://admin:admin@192.168.0.17:8111/authenticationTest.html?csrf
Accept: application/json

### 1. Create project
POST http://192.168.0.17:8111/app/rest/projects
Content-Type: application/json
Accept: application/json
X-TC-CSRF-Token:dafba980-a13e-4009-8f5f-d9bb29e9b991

{
  "parentProject": {
    "locator": "_Root"
  },
  "name": "name",
  "id": "id",
  "copyAllAssociatedSettings": true
}
###2. Create build configuration
POST http://192.168.0.17:8111/app/rest/buildTypes
Content-Type: application/json
Accept: application/json
X-TC-CSRF-Token: 7566ac80-f847-4dca-b497-be55acd4dd15

{
  "id": "id",
  "name": "print hello world",
  "project": {
    "id": "id"
  },
  "steps": {
    "step": [
      {
        "name": "print hello world",
        "type": "simpleRunner",
        "properties": {
          "property": [
            {
              "name": "script.content",
              "value": "echo 'Hello World!'"
            },
            {
              "name": "teamcity.step.mode",
              "value": "default"
            },
            {
              "name": "use.custom.script",
              "value": "true"
            }
          ]
        }
      }
    ]
  }
}
###3. Run build
POST http://192.168.0.17:8111/app/rest/buildQueue
Content-Type: application/json
Accept: application/json
X-TC-CSRF-Token:7566ac80-f847-4dca-b497-be55acd4dd15

{
  "buildType": {
    "id": "id"
  }
}
###3. Check build status
GET http://admin:admin@192.168.0.17:8111/app/rest/builds/id:106
Content-Type: application/json
Accept: application/json
X-TC-CSRF-Token:19bafa1e-62e7-43c9-95f4-783f3f0ad795
